### PR TITLE
Add batch-able command feature to PeriodCollection

### PR DESCRIPTION
**Pull request by briancharous**
This feature allows making multiple inserts/updates/deletes before releasing the write mutex on the tree so that if multiple constructive or destructive operations have to be performed in short sequence, the data in the tree is not in an inconsistent state (to the user).

### CODE REVIEW

**Comment by greg-mclain** [comment]
In what scenarios are we going to be using `Transaction` in availability? Would it be possible to instead have methods that take in a list of insertions or deletions? It seems dangerous to have the mutex lock/unlock in two separate method calls as it now yields control of the mutex to the "client" and they could indefinitely lock the tree.

**Comment by briancharous** [comment]
@greg-mclain That's a good point, I converted this from transactions to batch-able commands. I only implemented `Update` and `Delete` because I think there's a larger question around error handling if I were to support `Insert`, but since `Update` and `Delete` can't error, I can avoid that for now 😉

**Pull request merged**
